Month 9/step 1
Olegofr1endo/react-burger pull request #5
Opened 2023-02-22 08:40 UTC by Olegofr1endo

2023-02-22 10:20 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа!
Что понравилось:
- Есть автологин
- Данные формы отправляются по событию `onSubmit`
- Реализована защита роутов от авторизованных и не авторизованных пользователей.

Что необходимо исправить:
- [x] Лого в хедере сделайте ссылкой на главную страницу

- [ ] В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов".
- [ ] По заданию в случае успешной отправки запроса восстановления пароля пользователь должен перенаправляться на маршрут /reset-password, сейчас этого не происходит, пользователь так и остается на странице /forgot-password
- [ ] Держать пароль в куках - это не безопасно.
- [ ] Чтобы приходящий с сервера токен заносился всегда по пути "/" в куку, нужно в функцию setCookies передавать как значение параметра props аргумент {path="/"}:
setCookie('name', value, { path: '/' }).
Об этом можно прочитать здесь: https://learn.javascript.ru/cookie
Уничтожать токен при логауте пользователя нужно также по пути path: '/'.
<img width="1440" alt="Снимок экрана 2023-02-22 в 12 49 58" src="https://user-images.githubusercontent.com/60173362/220584227-8592a5dc-190e-4c50-aa87-9e2bc3d3cde0.png">
- [ ] При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.

**Можно лучше**
- [ ] Если во время отправки данных формы произошла ошибка, то её стоит показывать пользователю сообщая что пошло не так. Например при регистрации если пользователь ввел неправильные данные необходимо показывать об этом сообщение.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-22 10:20 UTC, andryxxa93 commented on src/components/form-page/form-page.jsx
> +  if (user) {
**Можно лучше**
создайте отдельный компонент OnlyUnAuthRoute, по аналогии c ProtectedRoute, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-02-22 10:34 UTC, Olegofr1endo commented on src/components/form-page/form-page.jsx
> +  if (user) {
Mercy за удобный чек-лист

2023-02-22 19:17 UTC, Olegofr1endo commented
По хранению паролей пока никакой теории не давали. Из внешних источников узнал что пароли шифруются и хранятся в куки, так ли это?

2023-02-23 05:34 UTC, andryxxa93 commented
> По хранению паролей пока никакой теории не давали. Из внешних источников узнал что пароли шифруются и хранятся в куки, так ли это?

Далеко не всегда и не везде. Вообще хранение любых личных данных в куках или localstorage не безопасно. Так как это не хранилище redux которое очищается сразу при закрытии страницы.

2023-02-23 05:36 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-01 10:32 UTC, merged